# Infrastructure Configuration for Production Environment

# Environment Settings
env:
  # Workspace Naming
  namespace: mlopslite  # Note: Keep short, storage accounts have 24 char limit
  postfix: prod  # Environment identifier
  location: westus  # Azure region
  environment: prod

  # Feature Flags
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # GitHub Actions Runner
  runner_image: ubuntu-latest

  # Azure Authentication
  # These values will be set in GitHub Secrets
  # AZURE_CREDENTIALS: Service principal details
  # AZURE_SUBSCRIPTION_ID: Subscription ID

  # Resource Names
  # Using GitHub Actions contexts and env variables: ${GITHUB_ENV}
  resource_group: rg-${namespace}-${postfix}
  aml_workspace: mlw-${namespace}-${postfix}
  application_insights: mlw-${namespace}-${postfix}
  key_vault: kv-${namespace}-${postfix}
  container_registry: cr${namespace}${postfix}
  storage_account: st${namespace}${postfix}

  # Terraform Settings
  terraform:
    version: 1.5.0
    working_dir: infrastructure
    state:
      resource_group: rg-${namespace}-${postfix}-tf
      storage_account: st${namespace}${postfix}tf
      container_name: tfstate
      key: prod.tfstate

  # Tags
  tags:
    environment: production
    project: mlops
    provisioner: terraform
    source: github-actions
