name: mlops-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    # Development tools
    - pre-commit==2.19.0
    - black==22.3.0
    - flake8==4.0.1
    - isort==5.10.1

    # Azure ML SDK and CLI
    - azure-ai-ml
    - azure-cli
    - azure-storage-blob>=12.10.0
    - azure-storage-file-share>=12.5.0
    - azure-storage-queue>=12.3.0
    - azure-storage-file-datalake>=12.2.0
    - azureml-mlflow

    # Data science dependencies
    - pandas
    - scikit-learn
    - matplotlib
    - joblib
    - pyarrow

    # Project requirements (from requirements.txt)
    - -r requirements.txt
