$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: ${TRAINING_ENV_NAME}

# Base image for the environment
# Default: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
image: ${BASE_IMAGE}

# Path to the conda environment file
conda_file: ${CONDA_ENV_PATH}
description: Environment created from a Docker image plus Conda environment to train taxi model.
